# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3ee289dd6ed4be3e56521cf90b6e52a38c49879501f6b4eaba6a90703f3e5d7ab2bf40bb2e8c44dbd5050863b3f76e23afcf90fc8149d714ce98d23b4a57573

test:
  secret_key_base: 4137448e8ff4b6a342cc41ae459227eead2a5f2d0397ed4686d0f58a8f8bb672ac02de735906ea0bf2462de4dc61b8392a8c22862c8130ef8c44a7245cce357b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
